string file
string[] contact_fingers #valid entries: TH,FF,MF,RF,LF - indicates which fingers have to be in contact in order to establish the grasp
---
bool success

#file
#==============
#relative file path to the .txt file specifying the trajectory

